name: Get Voice List Test

on:
  workflow_dispatch:  # 允许手动触发
#   schedule:
#     - cron: '0 0 * * *'  # 每天运行一次

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.1'
      - name: Run Voice List Test
        env:
          TOKEN: ${{ secrets.token }}
        run: |
          cd voice
          go test -v -timeout 10h -run TestVoice
      - name: Upload Downloads
        uses: actions/upload-artifact@v3
        with:
          name: voice-downloads
          path: downloads/
          retention-days: 7  # 保存7天