name: TTS Text File

on:
  workflow_dispatch:

jobs:
  text-file-to-speech:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.1'
      - name: Run TTS
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          go run main.go 
      - name: Upload Downloads
        uses: actions/upload-artifact@v4
        with:
          name: voice-downloads
          path: |
            ${{ github.workspace }}/**/*.mp3
            ${{ github.workspace }}/**/*.log
          retention-days: 7  # 保存7天