name: TTS

on:
  workflow_dispatch:
    inputs:
      voice_id:
        description: '语音ID'
        required: true
        type: string
        default: '7426720361733013513'
      text:
        description: '要转换的文本'
        required: true
        type: string
        default: '这是一个调用扣子API的项目'
      speed:
        description: '语速'
        required: true
        type: string
        default: '1.1'

jobs:
  tts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.1'
      - name: Run TTS
        env:
          TOKEN: ${{ secrets.TOKEN }}
          VOICE_ID: ${{ github.event.inputs.voice_id }}
          TEXT: ${{ github.event.inputs.text }}
          SPEED: ${{ github.event.inputs.speed }}
        run: |
          go run main.go ${VOICE_ID} ${TEXT} ${SPEED}
      - name: Upload Downloads
        uses: actions/upload-artifact@v4
        with:
          name: voice-downloads
          path: |
            ${{ github.workspace }}/**/*.mp3
            ${{ github.workspace }}/**/*.log
          retention-days: 7  # 保存7天